apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nexus-namespace.yaml
  - nexus-operator-subscription.yaml
  - nexus-instance.yaml
  - nexus-ui-route.yaml
  - nexus-docker-service.yaml
  - nexus-docker-route.yaml

configMapGenerator:
  - name: nexus-vars
    envs:
      - values.env

generatorOptions:
  disableNameSuffixHash: true

replacements:
  - source:
      kind: ConfigMap
      name: nexus-vars
      fieldPath: data.NEXUS_UI_HOST
    targets:
      - select:
          kind: Route
          name: nexus-ui
        fieldPaths:
          - spec.host

  - source:
      kind: ConfigMap
      name: nexus-vars
      fieldPath: data.NEXUS_REGISTRY_HOST
    targets:
      - select:
          kind: Route
          name: nexus-registry
        fieldPaths:
          - spec.host
