apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# All Nexus-related manifests
resources:
  - nexus-namespace.yaml
  - nexus-operator-subscription.yaml
  - nexus-instance.yaml
  - nexus-ui-route.yaml
  - nexus-docker-service.yaml
  - nexus-docker-route.yaml

# Generate a ConfigMap from values.env
configMapGenerator:
  - name: nexus-config
    envs:
      - values.env

# Expose values from ConfigMap as Kustomize vars
vars:
  - name: NEXUS_UI_HOST
    objref:
      kind: ConfigMap
      name: nexus-config
      apiVersion: v1
    fieldref:
      fieldPath: data.NEXUS_UI_HOST

  - name: NEXUS_REGISTRY_HOST
    objref:
      kind: ConfigMap
      name: nexus-config
      apiVersion: v1
    fieldref:
      fieldPath: data.NEXUS_REGISTRY_HOST
